---
- name: BIG-IP Refresh license
  hosts: lb
  connection: local
  gather_facts: false

  tasks:
    - name: Setup provider
      set_fact:
        provider:
          server: "{{private_ip}}"
          user: "{{ansible_user}}"
          password: "{{ansible_password}}"
          server_port: 443
          validate_certs: false
          no_f5_teem: false
                    
    - name: Refresh license
      f5networks.f5_modules.bigip_device_license:
        provider: "{{provider}}"
        license_key: "{{f5_reg_key}}"
        accept_eula: true
        force: true
        license_server: "activate.f5.com"
        state: present
        # issue with license servers, changed to present
        #state: latest
      delegate_to: localhost
