---
- name: BIG-IP Upload and Install Update
  hosts: lb
  gather_facts: false

  tasks:
    - name: Setup provider
      set_fact:
        provider:
          server: "{{private_ip}}"
          user: "{{ansible_user}}"
          password: "{{ansible_password}}"
          server_port: 443
          validate_certs: false
          
    - name: Store iso md5 hash
      set_fact:
        trusted_iso_md5: "{{ lookup('file', '/home/ubuntu/dev/isos/BIGIP-15.1.10-0.0.3.iso.md5').split(' ').0 }}"

    - name: Print iso md5 hash
      debug:
        msg: "{{ trusted_iso_md5 }}"

    - name: Upload image to device
      bigip_software_image:
        image: /home/ubuntu/dev/isos/BIGIP-15.1.10-0.0.3.iso
        provider: "{{provider}}"
      delegate_to: localhost

    - name: Get checksum
      shell: md5sum /shared/images/BIGIP-15.1.10-0.0.3.iso
      register: checksum
      failed_when: checksum.rc != 0
    
    - name: Store uploaded iso md5
      set_fact:
        uploaded_iso_md5: "{{ checksum.stdout.split(' ').0 }}"
      
    - name: Print Checksums
      debug:
        msg: 
          - "calulated md5sum is {{uploaded_iso_md5}}"
          -  "trusted md5sum is {{trusted_iso_md5}}"

    - name: Ensure an existing image is installed in specified volume
      bigip_software_install:
        image: BIGIP-15.1.10-0.0.3.iso
        volume: HD1.2
        state: installed
        provider: "{{provider}}"
      delegate_to: localhost

    - name: Activate the new image and reboot into that volume
    # For some reason this doesn't activate or reboot the system.  Issue #2374 has been opened to investigate
      bigip_software_install:
        image: BIGIP-15.1.10-0.0.3.iso
        volume: HD1.2
        state: activated
        provider: "{{provider}}"
      delegate_to: localhost

    
