---
- name: BIG-IP Upload and Install Update
  hosts: lb
  connection: local
  gather_facts: false

  tasks:
    - name: Setup provider
      set_fact:
        provider:
          server: "{{private_ip}}"
          user: "{{ansible_user}}"
          password: "{{ansible_password}}"
          server_port: 443
          validate_certs: false

    - name: Get iso md5 hash
      debug:
        msg: "{{lookup('file', '/home/ubuntu/dev/isos/BIGIP-15.1.10-0.0.3.iso.md5').split(' ').0}}"

    - name: Upload image to device
      bigip_software_image:
        image: /home/ubuntu/dev/isos/BIGIP-15.1.10-0.0.3.iso
        provider: "{{provider}}"
      delegate_to: localhost

    - name: Get checksum
      shell: md5sum /home/ubuntu/dev/isos/BIGIP-15.1.10-0.0.3.iso
      register: checksum
      failed_when: checksum.stdout.split(' ').0 != lookup('file', '/home/ubuntu/dev/isos/BIGIP-15.1.10-0.0.3.iso.md5').split(' ').0
      
    - name: Print Checksums
      debug:
        msg: 
          - "calulated md5sum is {{checksum.stdout.split(' ').0}}"
          -  "trusted md5sum is {{lookup('file', '/home/ubuntu/dev/isos/BIGIP-15.1.10-0.0.3.iso.md5').split(' ').0}}"

    - name: Ensure an existing image is installed in specified volume
      bigip_software_install:
        image: BIGIP-15.1.10-0.0.3.iso
        volume: HD1.2
        state: installed
        provider: "{{provider}}"
      delegate_to: localhost

    - name: Activate the new image and reboot into that volume
    # For some reason this doesn't activate or reboot the system.  Issue #2374 has been opened to investigate
      bigip_software_install:
        image: BIGIP-15.1.10-0.0.3.iso
        volume: HD1.2
        state: activated
        provider: "{{provider}}"
      delegate_to: localhost

    
