---
- name: "Get bigip status of virtuals, pools, nodes, and routes - initial state"
  hosts: ssh
  gather_facts: false
  vars:
    # filename is built to hold the report name.  Its timestamped and designated with BEFORE which is used in comparison
    # script_file is the script that is echoed on the device and ran to collect information
    # data_file is the out of the script file or the report.  Note this goes to a mounted directory in the EE!  Important.
    # device_working_dir, and report_dir are defined in the hosts/inventory
    filename: "{{inventory_hostname}}-{{ lookup('pipe', 'date +%FT%H%MZ') }}-BEFORE.log"
    script_file: "{{device_working_dir}}/data_collection_script.sh"
    data_file: "{{device_working_dir}}/{{filename}}"
  roles:
    #- roles/general/snapshot


- name: Create UCS/backup and save locally off-box
  hosts: lb
  #gather_facts: false
  vars:
    ucsfilename: "{{inventory_hostname}}-{{ lookup('pipe', 'date +%FT%H%MZ') }}-backup.ucs"

  roles:
  #  - roles/f5/save-config

- name: BIG-IP Refresh license
  hosts: lb
  gather_facts: false

  roles:
  - roles/f5/refresh-license


- name: "Get bigip status of virtuals, pools, nodes, and routes - final state"
  hosts: ssh
  gather_facts: false
  vars:
    # filename is built to hold the report name.  Its timestamped and designated with AFTER which is used in comparison
    # script_file is the script that is echoed on the device and ran to collect information
    # data_file is the out of the script file or the report.  Note this goes to a mounted directory in the EE!  Important.
    # device_working_dir, and report_dir are defined in the hosts/inventory
    filename: "{{inventory_hostname}}-{{ lookup('pipe', 'date +%FT%H%MZ') }}-AFTER.log"
    script_file: "{{device_working_dir}}/data_collection_script.sh"
    data_file: "{{device_working_dir}}/{{filename}}"
  roles:
    #- roles/general/snapshot

- name: "Compare the two snapshots"
  hosts: lb
  gather_facts: false
  roles:
    #- roles/general/compare-snapshot
